### ISSUE TITLE
TypeError: ("<lambda>() got an unexpected keyword argument 'result_type'", 'occurred at index chr1-10000-10468')

### ISSUE THREAD

**Issue by arton2008** [Oshlack/STRetch#65]
Hi,
I'm generating a pipeline using STRetch. When I run STRetch on fastqs, it fails in the last step (estimateSTR.py) with the following error. I searched the error and apparently this might be related to pandas's version so I updated pandas but I'm still getting the error. I would appreciate your help.

```Processing 1 samples
Traceback (most recent call last):
  File "/STRetch/scripts/estimateSTR.py", line 411, in <module>
    main()
  File "/STRetch/scripts/estimateSTR.py", line 335, in main
    pvals = z.apply(lambda z_row: [norm.sf(x) for x in z_row], axis=1, result_type='broadcast') # apply to each row
  File "/STRetch/tools/miniconda/envs/STR/lib/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/STRetch/tools/miniconda/envs/STR/lib/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/STRetch/tools/miniconda/envs/STR/lib/python3.6/site-packages/pandas/core/frame.py", line 4854, in f
    return func(x, *args, **kwds)
TypeError: ("<lambda>() got an unexpected keyword argument 'result_type'", 'occurred at index chr1-10000-10468')
```

**Comment by hdashnow** [comment]
Hi @arton2008 I haven't been able to replicate that error with the test data. I notice that I'm on Python 3.7 and you're using 3.6. However, I would expect that to be recent enough.

Would you mind running the install test to see if that works?
https://github.com/Oshlack/STRetch/wiki/Installing-STRetch

**Comment by arton2008** [comment]
Hi Harriet. I just ran the install test and it gave a similar error:

```Processing 5 samples
Traceback (most recent call last):
  File "/STRetch/scripts/estimateSTR.py", line 411, in <module>
    main()
  File "/STRetch/scripts/estimateSTR.py", line 335, in main
    pvals = z.apply(lambda z_row: [norm.sf(x) for x in z_row], axis=1, result_type='broadcast') # apply to each row
  File "/STRetch/tools/miniconda/envs/STR/lib/python3.6/site-packages/pandas/core/frame.py", line 4877, in apply
    ignore_failures=ignore_failures)
  File "/STRetch/tools/miniconda/envs/STR/lib/python3.6/site-packages/pandas/core/frame.py", line 4973, in _apply_standard
    results[i] = func(v)
  File "/STRetch/tools/miniconda/envs/STR/lib/python3.6/site-packages/pandas/core/frame.py", line 4854, in f
    return func(x, *args, **kwds)
TypeError: ("<lambda>() got an unexpected keyword argument 'result_type'", 'occurred at index chr13-70713515-70713561')
ERROR: Command failed with exit status = 1 :
```

**Comment by arton2008** [comment]
We managed to solve the problem. We were using an older version of STRetch and when we ran the newer version the pipeline completed successfully.

**Comment by hdashnow** [comment]
Glad to hear it! Thanks for the update
